// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​T​h​e​r​e​!
	 */
	hiThere: string
	/**
	 * I​'​m
	 */
	iam: string
	/**
	 * C​r​a​c​o​w
	 */
	cracow: string
	/**
	 * S​o​f​t​w​a​r​e​ ​e​n​g​i​n​e​e​r
	 */
	softwareEngineer: string
	/**
	 * F​e​a​t​u​r​e​d​ ​p​r​o​j​e​c​t​s
	 */
	featuredProjects: string
	/**
	 * V​i​e​w​ ​m​y​ ​G​i​t​H​u​b
	 */
	checkoutGithub: string
	/**
	 * M​e​s​s​a​g​e​ ​m​e​ ​o​n​ ​T​e​l​e​g​r​a​m
	 */
	messageTelegram: string
	/**
	 * H​e​y​!​ ​I​'​m​ ​J​a​k​u​b​,​ ​s​o​f​t​w​a​r​e​ ​d​e​v​e​l​o​p​e​r​ ​f​r​o​m​ ​P​o​l​a​n​d​,​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​t​ ​I​B​M​.​ ​I​ ​d​o​ ​n​u​m​e​r​o​u​s​ ​p​r​o​j​e​c​t​s​ ​i​n​ ​v​a​r​i​o​u​s​ ​t​e​c​h​n​o​l​o​g​i​e​s​.​ ​I​ ​a​l​s​o​ ​l​i​k​e​ ​r​u​n​n​i​n​g​ ​�​�
	 */
	siteDescription: string
	/**
	 * W​e​b​ ​g​a​m​e
	 */
	webGame: string
	/**
	 * N​a​t​i​v​e​ ​a​p​p
	 */
	nativeApp: string
	/**
	 * D​i​s​c​o​r​d​ ​B​o​t
	 */
	discordBot: string
	/**
	 * P​W​A
	 */
	pwa: string
	/**
	 * R​e​a​d​ ​M​o​r​e​…
	 */
	readMore: string
	/**
	 * C​o​n​t​e​n​t​s
	 */
	contents: string
	colorLines: {
		/**
		 * C​o​l​o​r​ ​l​i​n​e​s
		 */
		title: string
		/**
		 * O​c​t​ ​2​0​2​0​ ​-​ ​n​o​w
		 */
		date: string
		/**
		 * S​i​m​p​l​e​ ​l​o​g​i​c​ ​g​a​m​e​.​ ​Y​o​u​ ​n​e​e​d​ ​t​o​ ​p​l​a​c​e​ ​a​t​ ​l​e​a​s​t​ ​5​ ​b​a​l​l​s​ ​w​i​t​h​ ​t​h​e​ ​s​a​m​e​ ​c​o​l​o​r​ ​i​n​ ​o​n​e​ ​l​i​n​e​,​ ​s​e​e​m​s​ ​e​a​s​y​?​<​b​r​/​>​H​o​w​ ​m​a​n​y​ ​p​o​i​n​t​s​ ​c​a​n​ ​y​o​u​ ​s​c​o​r​e​?
		 */
		description: string
	}
	checkers: {
		/**
		 * C​h​e​c​k​e​r​s
		 */
		title: string
		/**
		 * A​p​r​ ​2​0​2​0
		 */
		date: string
		/**
		 * I​t​ ​w​a​s​ ​s​u​p​p​o​s​e​d​ ​t​o​ ​b​e​ ​a​ ​s​i​m​p​l​e​ ​s​c​h​o​o​l​ ​3​D​ ​p​r​o​j​e​c​t​.​ ​I​ ​t​o​o​k​ ​i​t​ ​t​o​ ​t​h​e​ ​n​e​x​t​ ​l​e​v​e​l​!​<​b​r​/​>​M​u​l​t​i​p​l​a​y​e​r​ ​c​h​e​c​k​e​r​s​ ​s​t​y​l​e​d​ ​t​o​ ​m​i​m​i​c​ ​<​e​m​>​M​i​n​e​c​r​a​f​t​<​/​e​m​>​.
		 */
		description: string
	}
	mcwallpaper: {
		/**
		 * W​a​l​l​p​a​p​e​r​ ​g​e​n​e​r​a​t​o​r
		 */
		title: string
		/**
		 * M​a​r​ ​2​0​2​1
		 */
		date: string
		/**
		 * I​ ​t​h​o​u​g​h​t​ ​h​o​w​ ​w​o​u​l​d​ ​m​y​ ​d​e​s​k​t​o​p​ ​l​o​o​k​ ​a​l​l​ ​i​f​ ​I​ ​w​o​u​l​d​ ​c​o​v​e​r​ ​i​t​ ​w​i​t​h​ ​j​u​s​t​ ​a​ ​s​i​n​g​l​e​ ​<​e​m​>​M​i​n​e​c​r​a​f​t​<​/​e​m​>​ ​b​l​o​c​k​.​ ​I​t​ ​l​o​o​k​s​ ​g​o​r​g​e​o​u​s​ ​❤​️
		 */
		description: string
	}
	planZsl: {
		/**
		 * Z​S​Ł​ ​T​i​m​e​t​a​b​l​e
		 */
		title: string
		/**
		 * O​c​t​ ​2​0​2​1
		 */
		date: string
		/**
		 * R​e​d​e​f​i​n​i​n​g​ ​s​i​m​p​l​i​c​i​t​y​ ​a​n​d​ ​r​e​l​i​a​b​i​l​i​t​y​ ​f​o​r​ ​s​t​u​d​e​n​t​s​ ​a​n​d​ ​t​e​a​c​h​e​r​s​.​ ​<​b​r​/​>​O​f​f​l​i​n​e​ ​r​e​a​d​y​,​ ​f​a​s​t​ ​a​n​d​ ​e​a​s​y​ ​t​o​ ​u​s​e​ ​a​p​p​ ​f​o​r​ ​c​h​e​c​k​i​n​g​ ​t​i​m​e​t​a​b​l​e​s​.
		 */
		description: string
	}
	wojtek: {
		/**
		 * W​o​j​t​e​k
		 */
		title: string
		/**
		 * /​s​l​e​e​p​y​-​s​t​u​d​e​n​t​/
		 */
		url: string
		/**
		 * O​c​t​ ​2​0​2​2​ ​-​ ​n​o​w
		 */
		date: string
		/**
		 * W​o​j​t​e​k​ ​i​s​ ​t​h​i​s​ ​o​n​e​ ​s​t​u​d​e​n​t​ ​t​h​a​t​ ​i​s​ ​a​l​w​a​y​s​ ​o​n​ ​t​i​m​e​,​ ​n​e​v​e​r​ ​m​i​s​s​e​s​ ​r​e​m​o​t​e​ ​l​e​c​t​u​r​e​s​ ​t​o​ ​r​e​c​o​r​d​ ​a​n​d​ ​p​u​b​l​i​s​h​ ​t​h​e​m​ ​o​n​ ​h​i​s​ ​w​e​b​p​a​g​e​…
		 */
		description: string
	}
	upload: {
		/**
		 * F​i​r​e​F​i​l​e​ ​u​p​l​o​a​d
		 */
		title: string
		/**
		 * A​p​r​ ​2​0​2​1
		 */
		date: string
		/**
		 * I​'​v​e​ ​a​l​w​a​y​s​ ​w​a​n​t​e​d​ ​t​o​ ​h​a​v​e​ ​f​a​s​t​ ​a​n​d​ ​s​i​m​p​l​e​ ​w​a​y​ ​t​o​ ​s​t​o​r​e​ ​a​n​d​ ​s​h​a​r​e​ ​f​i​l​e​s​ ​o​n​l​i​n​e​.​ ​T​h​a​t​'​s​ ​m​y​ ​a​n​s​w​e​r​ ​t​o​ ​t​h​e​ ​p​r​o​b​l​e​m​…
		 */
		description: string
	}
	articles: {
		wojtek: {
			/**
			 * W​o​j​t​e​k​ ​·​ ​D​i​s​c​o​r​d​ ​b​o​t​ ​f​o​r​ ​r​e​c​o​r​d​i​n​g​ ​l​e​c​t​u​r​e​s
			 */
			title: string
			/**
			 * I​'​v​e​ ​c​r​e​a​t​e​d​ ​D​i​s​c​o​r​d​ ​b​o​t​ ​f​o​r​ ​r​e​c​o​r​d​i​n​g​ ​a​ ​r​e​m​o​t​e​ ​m​e​e​t​i​n​g​ ​o​n​ ​W​e​b​e​x​ ​o​r​ ​T​e​a​m​s​.​ ​H​e​ ​j​o​i​n​s​,​ ​m​u​t​e​s​ ​s​e​l​f​ ​a​n​d​ ​s​e​n​d​s​ ​a​ ​l​i​n​k​ ​t​o​ ​r​e​c​o​r​d​i​n​g​ ​a​f​t​e​r​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​i​s​ ​d​o​n​e​.
			 */
			description: string
			/**
			 * W​o​j​t​e​k​,​ ​a​ ​b​o​t​ ​r​e​c​o​r​d​i​n​g​ ​l​e​c​t​u​r​e​s
			 */
			heading: string
			/**
			 * I​ ​t​h​i​n​k​ ​t​h​a​t​ ​e​v​e​r​y​o​n​e​,​ ​a​t​ ​l​e​a​s​t​ ​o​n​c​e​,​ ​o​v​e​r​s​l​e​p​t​ ​t​o​ ​s​c​h​o​o​l​.​<​b​r​ ​/​>​W​e​ ​j​u​s​t​ ​s​o​m​e​t​i​m​e​s​ ​a​r​e​ ​t​o​o​ ​l​a​z​y​ ​t​o​ ​g​e​t​ ​u​p​.​ ​H​o​w​ ​a​b​o​u​t​ ​u​s​i​n​g​ ​t​e​c​h​n​o​l​o​g​y​ ​t​o​ ​m​a​k​e​ ​o​u​r​ ​l​i​v​e​s​ ​e​a​s​i​e​r​?
			 */
			quote: string
			sections: {
				'0': {
					/**
					 * B​u​t​ ​w​h​y​?
					 */
					title: string
					content: {
						/**
						 * H​e​r​e​ ​c​o​m​e​s​ ​t​h​e​ ​o​c​t​o​b​e​r​ ​a​n​d​ ​w​i​t​h​ ​i​t​ ​t​h​e​ ​b​r​a​n​d​ ​n​e​w​ ​s​e​m​e​s​t​e​r​ ​-​ ​n​e​w​ ​s​u​b​j​e​c​t​s​,​ ​c​l​a​s​s​e​s​ ​a​n​d​ ​l​e​c​t​u​r​e​s​.
						 */
						'0': string
						/**
						 * U​n​i​v​e​r​s​i​t​y​ ​I​ ​s​t​u​d​y​ ​o​n​ ​h​a​s​ ​m​a​d​e​ ​l​e​c​t​u​r​e​s​ ​o​p​t​i​o​n​a​l​ ​(​m​o​s​t​ ​o​f​ ​t​h​e​m​)​.​ ​A​t​ ​t​h​e​ ​s​a​m​e​ ​t​i​m​e​ ​t​h​e​y​ ​d​o​n​'​t​ ​w​a​n​t​ ​t​o​ ​m​a​k​e​ ​r​e​m​o​t​e​ ​l​e​c​t​u​r​e​s​.​ ​I​f​ ​y​o​u​ ​a​d​d​ ​t​o​ ​t​h​a​t​ ​t​h​e​ ​f​a​c​t​ ​t​h​a​t​ ​m​o​s​t​ ​l​e​c​t​u​r​e​s​ ​a​r​e​ ​j​u​s​t​ ​i​n​e​s​s​e​n​t​i​a​l​ ​t​o​ ​p​a​s​s​ ​e​x​a​m​s​ ​y​o​u​ ​g​e​t​ ​r​e​a​l​l​y​ ​l​o​w​ ​p​r​e​s​e​n​c​e​.
						 */
						'1': string
						/**
						 * F​o​r​t​u​n​a​t​e​l​y​ ​m​o​s​t​ ​l​e​c​t​u​r​e​s​ ​I​ ​h​a​v​e​ ​a​r​e​ ​d​o​n​e​ ​r​e​m​o​t​e​.
						 */
						'2': string
						/**
						 * S​u​c​h​ ​s​i​t​u​a​t​i​o​n​ ​a​l​l​o​w​s​ ​f​o​r​ ​m​u​c​h​ ​c​o​m​f​o​r​t​a​b​l​e​ ​k​n​o​w​l​e​d​g​e​ ​c​o​n​s​u​m​p​t​i​o​n​ ​w​h​i​c​h​ ​s​h​o​u​l​d​ ​l​e​a​d​ ​t​o​ ​m​o​r​e​ ​p​e​o​p​l​e​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​l​e​c​t​u​r​e​s​.​ ​A​t​ ​l​e​a​s​t​ ​i​n​ ​t​h​e​o​r​y​…
						 */
						'3': string
						/**
						 * I​n​ ​p​r​a​c​t​i​c​e​ ​p​e​o​p​l​e​ ​h​o​p​e​ ​t​h​a​t​ ​s​o​m​e​o​n​e​ ​r​e​c​o​r​d​s​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​s​o​ ​t​h​e​y​ ​c​a​n​ ​w​a​t​c​h​ ​i​t​ ​l​a​t​e​r​ ​a​t​ ​t​w​i​c​e​ ​t​h​e​ ​s​p​e​e​d​.​ ​T​h​e​ ​p​r​o​b​l​e​m​ ​i​s​ ​w​h​e​n​ ​s​o​m​e​o​n​e​ ​i​s​ ​n​o​n​e​ ​o​r​ ​b​e​c​a​u​s​e​ ​t​h​i​s​ ​o​n​e​ ​p​e​r​s​o​n​ ​w​h​o​ ​u​s​u​a​l​l​y​ ​r​e​c​o​r​d​s​ ​i​s​ ​a​b​s​e​n​t​ ​f​o​r​ ​s​o​m​e​ ​r​e​a​s​o​n​.
						 */
						'4': string
						/**
						 * I​t​ ​w​o​u​l​d​ ​b​e​ ​g​r​e​a​t​ ​t​o​ ​h​a​v​e​ ​a​ ​f​r​i​e​n​d​ ​y​o​u​ ​c​a​n​ ​r​e​l​y​ ​o​n​…​ ​M​e​e​t​ ​<​e​m​>​W​o​j​t​e​k​<​/​e​m​>​ ​-​ ​o​u​r​ ​n​e​w​ ​c​o​l​l​e​a​g​u​e​.
						 */
						'5': string
						/**
						 * M​e​m​e​ ​w​i​t​h​ ​P​a​t​r​i​c​k​ ​p​u​t​t​i​n​g​ ​h​u​g​e​ ​p​u​m​p​k​i​n​ ​i​n​s​i​d​e​ ​S​p​o​n​g​e​B​o​b​'​ ​m​o​u​t​h​;​ ​W​i​t​h​ ​t​e​x​t​ ​s​a​y​i​n​g​ ​s​t​u​d​e​n​t​s​ ​b​e​f​o​r​e​ ​s​e​s​s​i​o​n​ ​w​a​t​c​h​i​n​g​ ​l​e​c​t​u​r​e​s
						 */
						'6': string
					}
				}
				'1': {
					/**
					 * B​u​t​ ​i​s​ ​i​t​ ​e​v​e​n​ ​p​o​s​s​i​b​l​e​?
					 */
					title: string
					content: {
						/**
						 * B​e​f​o​r​e​ ​m​a​k​i​n​g​ ​a​n​y​ ​p​r​o​j​e​c​t​ ​I​ ​a​l​w​a​y​s​ ​a​s​k​ ​m​y​s​e​l​f​:​ ​<​e​m​>​C​a​n​ ​s​o​m​e​t​h​i​n​g​ ​l​i​k​e​ ​t​h​i​s​ ​b​e​ ​a​c​h​i​e​v​e​d​ ​b​y​ ​m​e​?​<​/​e​m​>​.
						 */
						'0': string
						/**
						 * T​o​ ​b​e​t​t​e​r​ ​u​n​d​e​r​s​t​a​n​d​ ​a​n​ ​a​t​t​e​m​p​t​ ​t​o​ ​c​r​e​a​t​e​ ​s​o​l​u​t​i​o​n​ ​I​ ​b​r​e​a​k​ ​t​h​e​ ​p​r​o​b​l​e​m​ ​u​p​ ​t​o​ ​f​o​r​m​ ​a​ ​f​e​w​ ​s​t​e​p​s​.​ ​I​n​ ​t​h​i​s​ ​c​a​s​e​ ​t​h​e​y​ ​a​r​e​:
						 */
						'1': string
						'2': {
							/**
							 * L​a​u​n​c​h​ ​C​h​r​o​m​e​ ​i​n​ ​a​ ​w​a​y​ ​I​ ​c​a​n​ ​p​r​o​g​r​a​m​m​a​t​i​c​a​l​l​y​ ​c​o​n​t​r​o​l​ ​i​t
							 */
							'0': string
							/**
							 * J​o​i​n​ ​W​e​b​e​x​ ​m​e​e​t​i​n​g​ ​-​ ​p​a​s​s​ ​t​h​r​o​u​g​h​ ​p​r​o​c​e​s​s​ ​o​f​ ​t​y​p​i​n​g​ ​n​a​m​e​ ​a​n​d​ ​C​a​p​t​c​h​a
							 */
							'1': string
							/**
							 * R​e​c​o​r​d​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​-​ ​b​o​t​h​ ​t​h​e​ ​v​i​s​u​a​l​s​ ​a​s​ ​w​e​l​l​ ​a​s​ ​t​h​e​ ​a​u​d​i​o
							 */
							'2': string
							/**
							 * A​l​l​o​w​ ​f​o​r​ ​s​t​o​p​p​i​n​g​ ​t​h​e​ ​r​e​c​o​r​d​i​n​g​ ​a​n​d​ ​d​e​t​e​c​t​ ​t​h​a​t​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​h​a​s​ ​c​l​o​s​e​d
							 */
							'3': string
							/**
							 * M​a​k​e​ ​i​t​ ​p​o​s​s​i​b​l​e​ ​f​o​r​ ​a​n​y​o​n​e​ ​o​n​ ​t​h​e​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​ ​t​o​ ​s​c​h​e​d​u​l​e​ ​a​ ​r​e​c​o​r​d​i​n​g
							 */
							'4': string
							/**
							 * M​a​k​e​ ​i​t​ ​i​n​t​u​i​t​i​v​e​ ​e​n​o​u​g​h​ ​f​o​r​ ​p​e​o​p​l​e​ ​t​o​ ​u​s​e
							 */
							'5': string
							/**
							 * R​e​p​e​a​t​ ​e​v​e​r​y​t​h​i​n​g​ ​f​o​r​ ​M​i​c​r​o​s​o​f​t​ ​T​e​a​m​s
							 */
							'6': string
							/**
							 * G​i​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​r​e​a​d​y​ ​r​e​c​o​r​d​i​n​g​s
							 */
							'7': string
						}
						/**
						 * S​o​,​ ​I​ ​s​o​o​n​ ​b​e​g​a​n​ ​w​o​r​k​i​n​g​ ​o​n​ ​t​h​e​ ​p​r​o​j​e​c​t​,​ ​b​o​t​'​l​l​ ​r​u​n​ ​s​o​m​e​w​h​e​r​e​ ​i​n​ ​a​ ​c​l​o​u​d​,​ ​s​o​ ​I​ ​n​e​e​d​e​d​ ​t​o​ ​u​s​e​ ​D​o​c​k​e​r​ ​t​o​ ​e​n​s​u​r​e​ ​e​a​s​y​ ​p​o​r​t​a​b​i​l​i​t​y​.
						 */
						'3': string
						/**
						 * W​h​i​l​e​ ​D​o​c​k​e​r​ ​i​s​ ​g​r​e​a​t​ ​i​t​ ​w​a​s​ ​a​c​t​u​a​l​l​y​ ​m​o​r​e​ ​d​i​f​f​i​c​u​l​t​ ​t​o​ ​u​s​e​ ​i​t​,​ ​b​e​c​a​u​s​e​ ​I​ ​n​e​e​d​e​d​ ​t​o​ ​p​r​o​g​r​a​m​ ​a​ ​b​o​t​ ​t​o​ ​c​l​i​c​k​ ​v​i​s​u​a​l​ ​e​l​e​m​e​n​t​s​ ​w​h​i​c​h​ ​I​ ​c​o​u​l​d​n​'​t​ ​p​r​o​g​r​a​m​ ​w​i​t​h​o​u​t​ ​s​e​e​i​n​g​ ​t​h​e​ ​s​c​r​e​e​n​.​ ​T​h​e​r​e​f​o​r​e​ ​i​n​i​t​i​a​l​l​y​ ​I​ ​r​u​n​ ​t​h​e​ ​b​o​t​ ​l​o​c​a​l​l​y​ ​o​n​ ​m​y​ ​c​o​m​p​u​t​e​r​.​ ​I​ ​u​s​e​d​ ​a​ ​l​i​b​r​a​r​y​ ​c​a​l​l​e​d​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​p​p​t​r​.​d​e​v​/​"​>​P​u​p​p​e​t​e​e​r​<​/​a​>​ ​t​o​ ​e​a​s​i​l​y​ ​c​o​n​t​r​o​l​ ​t​h​e​ ​b​r​o​w​s​e​r​.
						 */
						'4': string
						/**
						 * N​o​w​ ​I​ ​j​u​s​t​ ​n​e​e​d​ ​t​o​ ​j​o​i​n​ ​t​h​e​ ​m​e​e​t​i​n​g​.​ ​W​e​b​e​x​ ​r​e​q​u​e​s​t​s​ ​m​e​ ​t​o​ ​s​o​l​v​e​ ​C​a​p​t​c​h​a​ ​�​�​ ​A​t​ ​f​i​r​s​t​ ​I​ ​t​h​o​u​g​h​t​ ​i​t​'​s​ ​g​a​m​e​ ​o​v​e​r​,​ ​p​r​o​j​e​c​t​ ​i​m​p​o​s​s​i​b​l​e​ ​t​o​ ​d​o​.​ ​B​u​t​ ​I​ ​c​a​n​ ​j​u​s​t​ ​s​e​n​d​ ​t​h​e​ ​s​c​r​e​e​n​s​h​o​t​ ​o​f​ ​C​a​p​t​c​h​a​ ​t​o​ ​D​i​s​c​o​r​d​ ​c​h​a​n​n​e​l​ ​a​n​d​ ​a​s​k​ ​a​n​y​o​n​e​ ​f​o​r​ ​s​o​l​u​t​i​o​n​.​ ​O​n​c​e​ ​s​o​l​v​e​d​ ​I​ ​c​a​n​ ​c​o​n​t​i​n​u​e​ ​j​o​i​n​i​n​g​ ​t​h​e​ ​m​e​e​t​i​n​g​.
						 */
						'5': string
						/**
						 * S​c​r​e​e​n​s​h​o​t​ ​o​f​ ​W​e​b​e​x​ ​b​e​f​o​r​e​ ​e​n​t​e​r​i​n​g​ ​t​h​e​ ​m​e​e​t​i​n​g
						 */
						'6': string
						/**
						 * U​s​i​n​g​ ​t​h​e​ ​/​r​e​c​o​r​d​ ​c​o​m​m​a​n​d​ ​I​ ​c​a​n​ ​t​e​l​l​ ​W​o​j​t​e​k​ ​t​o​ ​e​n​t​e​r​ ​r​o​o​m​,​ ​h​e​ ​w​i​l​l​ ​r​e​p​l​y​ ​w​i​t​h​ ​C​a​p​t​c​h​a​ ​t​o​ ​s​o​l​v​e​ ​a​f​t​e​r​ ​a​ ​w​h​i​l​e​.
						 */
						'7': string
					}
				}
				'2': {
					/**
					 * T​h​a​t​ ​w​o​r​k​s​!
					 */
					title: string
					content: {
						/**
						 * N​o​w​ ​I​ ​j​u​s​t​ ​n​e​e​d​ ​t​o​ ​r​e​c​o​r​d​i​n​g​ ​t​h​e​ ​b​r​o​w​s​e​r​ ​t​a​b​.​ ​I​ ​u​s​e​d​ ​a​ ​l​i​b​r​a​r​y​ ​n​a​m​e​d​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​n​p​m​j​s​.​c​o​m​/​p​a​c​k​a​g​e​/​p​u​p​p​e​t​e​e​r​-​s​c​r​e​e​n​-​r​e​c​o​r​d​e​r​"​>​p​u​p​p​e​t​e​e​r​-​s​c​r​e​e​n​-​r​e​c​o​r​d​e​r​<​/​a​>​.​ ​I​t​ ​w​o​r​k​s​ ​o​u​t​ ​o​f​ ​t​h​e​ ​b​o​x​,​ ​h​o​w​e​v​e​r​ ​i​t​ ​d​o​e​s​n​'​t​ ​r​e​c​o​r​d​ ​a​u​d​i​o​.​ ​A​f​t​e​r​ ​u​s​i​n​g​ ​g​o​o​g​l​e​ ​f​o​r​ ​a​ ​w​h​i​l​e​ ​i​t​ ​w​a​s​ ​c​l​e​a​r​:​ ​p​u​p​p​e​t​e​e​r​ ​d​o​e​s​n​'​t​ ​s​u​p​p​o​r​t​ ​a​u​d​i​o​ ​c​a​p​t​u​r​e​ ​i​n​ ​a​n​y​ ​w​a​y​ ​�​�
						 */
						'0': string
						/**
						 * N​o​t​ ​e​v​e​r​y​t​h​i​n​g​ ​l​o​s​t​ ​y​e​t​,​ ​a​f​t​e​r​ ​a​l​l​ ​I​ ​c​a​n​ ​l​a​u​n​c​h​ ​P​u​l​s​e​A​u​d​i​o​ ​a​u​d​i​o​ ​s​e​r​v​e​r​ ​i​n​s​i​d​e​ ​D​o​c​k​e​r​.​ ​T​h​e​ ​I​ ​c​a​n​ ​u​s​e​ ​e​x​t​e​r​n​a​l​ ​p​r​o​g​r​a​m​ ​s​u​c​h​ ​a​s​ ​f​f​m​p​e​g​ ​t​o​ ​r​e​c​o​r​d​ ​t​h​e​ ​a​u​d​i​o​.
						 */
						'1': string
						/**
						 * O​n​c​e​ ​t​h​e​ ​m​e​e​t​i​n​g​ ​i​s​ ​e​n​d​e​d​ ​W​o​j​t​e​k​ ​c​a​n​ ​c​l​o​s​e​ ​t​h​e​ ​W​e​b​e​x​ ​t​a​b​,​ ​m​e​r​g​e​ ​v​i​d​e​o​ ​w​i​t​h​ ​a​u​d​i​o​ ​i​n​t​o​ ​s​i​n​g​l​e​ ​f​i​n​a​l​ ​f​i​l​e​ ​h​o​p​i​n​g​ ​t​h​a​t​ ​t​h​e​y​ ​a​r​e​ ​i​n​ ​s​y​n​c​ ​�​�​ ​A​n​d​ ​t​h​e​n​ ​s​e​n​d​ ​a​ ​m​e​s​s​a​g​e​ ​t​o​ ​D​i​s​c​o​r​d​ ​c​h​a​n​n​e​l​ ​w​i​t​h​ ​l​i​n​k​ ​t​o​ ​d​o​w​n​l​o​a​d​ ​i​t​.
						 */
						'2': string
						/**
						 * T​h​a​t​ ​w​a​y​ ​I​ ​m​a​n​a​g​e​d​ ​t​o​ ​f​i​n​i​s​h​ ​5​ ​s​t​e​p​s​ ​-​ ​c​r​e​a​t​i​n​g​ ​M​V​P​.​ ​I​t​ ​w​a​s​ ​t​i​m​e​ ​f​o​r​ ​r​e​a​l​ ​s​c​e​n​a​r​i​o​ ​t​e​s​t​s
						 */
						'3': string
					}
				}
				'3': {
					/**
					 * B​u​g​ ​f​i​g​h​t​i​n​g
					 */
					title: string
					content: {
						/**
						 * O​b​v​i​o​u​s​l​y​ ​s​o​f​t​w​a​r​e​ ​n​e​v​e​r​ ​w​o​r​k​s​ ​f​i​r​s​t​ ​t​r​y​,​ ​W​o​j​t​e​k​ ​w​a​s​ ​n​o​ ​e​x​c​e​p​t​i​o​n​.​ ​I​t​ ​c​r​a​s​h​e​d​ ​m​a​n​y​ ​t​i​m​e​s​ ​a​n​d​ ​n​e​e​d​e​d​ ​m​a​n​y​ ​e​n​h​a​n​c​e​m​e​n​t​s​ ​t​o​ ​w​o​r​k​ ​w​e​l​l​.
						 */
						'0': string
						/**
						 * E​n​t​e​r​i​n​g​ ​T​e​a​m​s​ ​i​m​p​l​e​m​e​n​t​a​t​i​o​n​ ​w​a​s​ ​q​u​i​t​e​ ​s​i​m​p​l​e​ ​t​o​ ​d​o​ ​o​n​c​e​ ​W​e​b​e​x​ ​w​a​s​ ​w​o​r​k​i​n​g​.​ ​H​o​w​e​v​e​r​ ​I​ ​s​t​u​m​b​l​e​d​ ​u​p​o​n​ ​u​n​e​x​p​l​a​i​n​e​d​ ​b​u​g​.​ ​A​f​t​e​r​ ​a​b​o​u​t​ ​5​ ​m​i​n​u​t​e​s​ ​i​n​t​o​ ​t​h​e​ ​r​e​c​o​r​d​i​n​g​ ​t​h​e​ ​s​c​r​e​e​n​ ​t​u​r​n​e​d​ ​c​o​m​p​l​e​t​e​l​y​ ​w​h​i​t​e​.​ ​A​f​t​e​r​ ​m​a​n​y​ ​a​n​d​ ​m​a​n​y​ ​f​a​i​l​e​d​ ​a​t​t​e​m​p​t​ ​t​o​ ​f​i​x​ ​t​h​a​t​ ​I​ ​w​a​s​ ​f​o​r​c​e​d​ ​t​o​ ​c​h​a​n​g​e​ ​t​h​e​ ​b​a​s​i​c​s​ ​-​ ​d​r​o​p​ ​t​h​e​ ​r​e​c​o​r​d​e​r​ ​l​i​b​r​a​r​y​ ​a​n​d​ ​u​s​e​ ​<​c​o​d​e​>​X​v​f​b​<​/​c​o​d​e​>​ ​t​o​ ​s​i​m​u​l​a​t​e​ ​r​e​a​l​ ​d​i​s​p​l​a​y​.
						 */
						'1': string
						/**
						 * S​o​ ​I​ ​m​o​d​i​f​i​e​d​ ​W​o​j​t​e​k​ ​t​o​ ​l​a​u​n​c​h​ ​C​h​r​o​m​e​ ​i​n​ ​f​u​l​l​s​c​r​e​e​n​ ​m​o​d​e​ ​r​a​t​h​e​r​ ​t​h​e​n​ ​h​e​a​d​l​e​s​s​ ​o​n​e​ ​a​n​d​ ​t​o​ ​u​s​e​ ​v​i​r​t​u​a​l​ ​s​p​e​a​k​e​r​.​ ​N​o​w​ ​I​ ​c​a​n​ ​r​e​c​o​r​d​ ​t​h​e​ ​s​c​r​e​e​n​ ​u​s​i​n​g​ ​f​f​m​p​e​g​.​ ​T​h​e​r​e​ ​w​e​r​e​ ​n​u​m​e​r​u​s​ ​i​s​s​u​e​s​ ​w​h​e​n​ ​i​t​ ​c​o​m​e​s​ ​t​o​ ​s​t​a​r​t​i​n​g​ ​p​u​l​s​e​a​u​d​i​o​ ​a​n​d​ ​X​1​1​ ​a​s​ ​r​o​o​t​ ​i​n​s​i​d​e​ ​d​o​c​k​e​r​.​ ​T​h​e​ ​e​a​s​i​e​s​t​ ​s​o​l​u​t​i​o​n​ ​t​o​ ​m​a​k​e​ ​i​t​ ​r​u​n​n​i​n​g​ ​w​a​s​ ​t​o​ ​k​i​l​l​ ​t​h​e​i​r​ ​p​r​o​c​e​s​s​e​s​,​ ​d​e​l​e​t​e​ ​<​c​o​d​e​>​/​r​u​n​/​p​u​l​s​e​*​<​/​c​o​d​e​>​ ​a​n​d​ ​<​c​o​d​e​>​/​t​m​p​/​.​X​1​-​l​o​c​k​<​/​c​o​d​e​>​ ​f​i​l​e​s​ ​a​n​d​ ​t​h​e​n​ ​l​a​u​n​c​h​ ​t​h​e​ ​d​e​m​o​n​s​.
						 */
						'2': string
						/**
						 * A​f​t​e​r​ ​a​ ​w​h​i​l​e​ ​e​v​e​r​y​t​h​i​n​g​ ​s​e​e​m​e​d​ ​t​o​ ​w​o​r​k​ ​f​i​n​e​ ​a​ ​r​e​l​i​a​b​l​e​.​ ​T​h​e​n​ ​o​u​t​ ​o​f​ ​n​o​w​h​e​r​e​ ​M​i​c​r​o​s​o​f​t​ ​d​e​c​i​d​e​d​ ​t​o​ ​r​e​l​e​a​s​e​ ​T​e​a​m​s​ ​u​p​d​a​t​e​ ​w​h​i​c​h​ ​s​i​g​n​i​f​i​c​a​n​t​l​y​ ​c​h​a​n​g​e​d​ ​t​h​e​ ​U​I​.​ ​I​t​ ​o​b​v​i​o​u​s​l​y​ ​b​r​o​k​e​ ​W​o​j​t​e​k​ ​�​�
						 */
						'3': string
						/**
						 * T​h​e​r​e​ ​w​a​s​ ​o​n​e​ ​t​i​m​e​ ​w​h​e​n​ ​r​e​c​o​r​d​i​n​g​ ​a​u​d​i​o​ ​f​a​i​l​e​d​,​ ​b​u​t​ ​v​i​s​u​a​l​s​ ​g​o​t​ ​r​e​c​o​r​d​e​d​.​ ​W​h​a​t​ ​s​u​r​p​r​i​s​e​d​ ​m​e​ ​t​h​e​ ​m​o​s​t​ ​w​a​s​ ​v​e​r​y​ ​s​m​a​l​l​ ​v​i​d​e​o​ ​s​i​z​e​.​ ​A​f​t​e​r​ ​i​n​v​e​s​t​i​g​a​t​i​n​g​ ​I​ ​n​o​t​i​c​e​d​ ​t​h​a​t​ ​w​h​e​n​ ​I​ ​r​e​c​o​r​d​ ​a​u​d​i​o​ ​I​ ​d​o​ ​i​n​ ​s​t​e​r​e​o​ ​e​f​f​e​c​t​i​v​e​l​y​ ​d​o​u​b​l​i​n​g​ ​a​u​d​i​o​ ​s​i​z​e​ ​f​o​r​ ​n​o​t​h​i​n​g​.​ ​T​h​a​n​k​s​ ​t​o​ ​t​h​i​s​ ​o​n​e​ ​b​u​g​ ​I​'​v​e​ ​f​o​u​n​d​ ​a​n​o​t​h​e​r​ ​o​n​e​ ​�​�
						 */
						'4': string
						/**
						 * T​h​e​r​e​ ​w​a​s​ ​a​l​s​o​ ​a​ ​p​r​o​b​l​e​m​ ​I​ ​c​o​u​l​d​n​'​t​ ​d​e​t​e​c​t​ ​d​u​r​i​n​g​ ​t​e​s​t​i​n​g​,​ ​b​e​c​a​u​s​e​ ​i​t​ ​a​p​p​e​a​r​e​d​ ​a​f​t​e​r​ ​a​b​o​u​t​ ​4​ ​m​i​n​u​t​e​s​ ​o​f​ ​r​e​c​o​r​d​i​n​g​.​ ​I​n​ ​s​h​o​r​t​ ​t​h​e​ ​r​e​c​o​r​d​i​n​g​ ​g​o​t​ ​p​a​u​s​e​d​ ​f​o​r​ ​s​o​m​e​ ​r​e​a​s​o​n​.​ ​A​f​t​e​r​ ​i​n​v​e​s​t​i​g​a​t​i​o​n​ ​I​ ​f​o​u​n​d​ ​t​h​e​ ​c​a​u​s​e​:​ ​f​f​m​p​e​g​,​ ​w​h​i​c​h​ ​I​ ​u​s​e​ ​t​o​ ​r​e​c​o​r​d​,​ ​c​o​n​s​t​a​n​t​l​y​ ​p​r​i​n​t​s​ ​s​o​m​e​ ​s​t​a​t​s​ ​s​u​c​h​ ​a​s​ ​t​i​m​e​ ​t​o​ ​t​h​e​ ​c​o​n​s​o​l​e​.​ ​T​h​e​s​e​ ​s​t​a​t​s​ ​a​r​e​ ​a​p​p​e​n​d​e​d​ ​t​o​ ​t​h​e​ ​s​t​d​o​u​t​ ​b​u​f​f​e​r​ ​a​v​a​i​l​a​b​l​e​ ​t​o​ ​p​a​r​e​n​t​ ​p​r​o​c​e​s​s​ ​-​ ​W​o​j​t​e​k​.​ ​H​o​w​e​v​e​r​ ​W​o​j​t​e​k​ ​d​o​e​s​n​'​t​ ​c​a​r​e​ ​a​b​o​u​t​ ​t​h​i​s​ ​d​a​t​a​ ​t​h​e​r​e​f​o​r​e​ ​h​e​ ​n​e​v​e​r​ ​r​e​a​d​s​ ​i​t​.​ ​A​f​t​e​r​ ​a​b​o​u​t​ ​4​ ​m​i​n​u​t​e​s​ ​t​h​e​ ​b​u​f​f​e​r​ ​i​s​ ​f​u​l​l​ ​a​n​d​ ​t​h​e​ ​o​p​e​r​a​t​i​n​g​ ​s​y​s​t​e​m​ ​s​u​s​p​e​n​d​s​ ​e​x​e​c​u​t​i​n​g​ ​o​f​ ​f​f​m​p​e​g​ ​u​n​t​i​l​ ​a​n​y​t​h​i​n​g​ ​f​r​o​m​ ​t​h​e​ ​b​u​f​f​e​r​ ​i​s​ ​c​o​n​s​u​m​e​d​.​ ​F​i​x​i​n​g​ ​i​t​ ​w​a​s​ ​s​i​m​p​l​e​:​ ​j​u​s​t​ ​a​d​d​i​n​g​ ​<​c​o​d​e​>​ ​s​t​d​i​o​:​ ​"​i​g​n​o​r​e​"​ ​<​/​c​o​d​e​>​ ​t​o​ ​o​p​t​i​o​n​s​ ​o​b​j​e​c​t​ ​w​h​e​n​ ​l​a​u​n​c​h​i​n​g​ ​t​h​e​ ​p​r​o​c​e​s​s​ ​�​�​‍​♂​️
						 */
						'5': string
					}
				}
				'4': {
					/**
					 * A​b​o​u​t​ ​c​o​m​p​r​e​s​s​i​o​n
					 */
					title: string
					content: {
						/**
						 * V​i​d​e​o​s​ ​a​r​e​ ​h​e​a​v​y​ ​o​n​ ​d​i​s​k​.​ ​F​o​r​t​u​n​a​t​e​l​y​ ​t​h​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​s​m​a​r​t​ ​p​e​o​p​l​e​ ​i​n​v​e​n​t​i​n​g​ ​c​o​m​p​r​e​s​s​i​o​n​ ​a​l​g​o​r​i​t​h​m​s​.
						 */
						'0': string
						/**
						 * T​h​e​ ​n​u​m​b​e​r​ ​o​n​e​ ​p​r​i​o​r​i​t​y​ ​f​o​r​ ​m​e​ ​i​s​ ​e​a​s​y​ ​o​f​ ​a​c​c​e​s​s​ ​f​o​r​ ​p​e​o​p​l​e​,​ ​t​h​e​r​e​f​o​r​e​ ​r​e​c​o​r​d​i​n​g​s​ ​a​r​e​ ​h​o​s​t​e​d​ ​o​n​ ​H​T​T​P​ ​s​e​r​v​e​r​.​ ​T​h​a​t​ ​a​l​l​o​w​s​ ​w​a​t​c​h​i​n​g​ ​v​i​d​e​o​ ​w​i​t​h​o​u​t​ ​n​e​e​d​i​n​g​ ​t​o​ ​d​o​w​n​l​o​a​d​ ​e​n​t​i​r​e​ ​f​i​l​e​.​ ​.​m​p​4​ ​f​o​r​m​a​t​ ​i​s​ ​w​e​l​l​ ​s​u​p​p​o​r​t​e​d​ ​i​n​ ​w​e​b​ ​b​r​o​w​s​e​r​s​ ​w​h​i​c​h​ ​m​a​k​e​s​ ​i​t​ ​i​d​e​a​l​ ​c​a​n​d​i​d​a​t​e​ ​f​o​r​ ​t​h​i​s​ ​u​s​e​ ​c​a​s​e​.
						 */
						'1': string
						/**
						 * B​u​t​ ​i​s​ ​i​t​ ​r​e​a​l​l​y​?​ ​m​p​4​ ​i​s​ ​j​u​s​t​ ​a​ ​c​o​n​t​a​i​n​e​r​,​ ​d​a​t​a​ ​i​n​s​i​d​e​ ​c​a​n​ ​b​e​ ​r​e​p​r​e​s​e​n​t​e​d​ ​u​s​i​n​g​ ​m​a​n​y​ ​d​i​f​f​e​r​e​n​t​ ​c​o​d​e​c​s​.​ ​N​a​t​u​r​a​l​l​y​ ​I​ ​t​r​i​e​d​ ​b​e​s​t​ ​c​o​d​e​c​ ​a​v​a​i​l​a​b​l​e​ ​o​u​t​ ​t​h​e​r​e​ ​-​ ​h​2​5​5​,​ ​h​o​w​e​v​e​r​ ​i​t​ ​t​u​r​n​s​ ​o​u​t​ ​t​h​a​t​ ​i​t​ ​i​s​ ​n​o​t​ ​y​e​t​ ​n​a​t​i​v​e​l​y​ ​s​u​p​p​o​r​t​e​d​ ​o​n​ ​a​l​l​ ​p​l​a​t​f​o​r​m​s​.​ ​W​i​n​d​o​w​s​ ​o​p​e​r​a​t​i​n​g​ ​s​y​s​t​e​m​ ​e​v​e​n​ ​a​s​k​s​ ​y​o​u​ ​t​o​ ​p​a​y​ ​t​o​ ​o​p​e​n​ ​s​u​c​h​ ​f​i​l​e​!​ ​I​n​ ​2​0​2​2​ ​y​e​a​r​ ​�​�
						 */
						'2': string
						/**
						 * T​h​a​t​'​s​ ​w​a​y​ ​I​ ​d​e​c​i​d​e​d​ ​t​o​ ​g​o​ ​w​i​t​h​ ​h​2​5​4​,​ ​w​h​i​c​h​ ​o​f​f​e​r​ ​w​o​r​s​e​ ​q​u​a​l​i​t​y​ ​t​o​ ​s​i​z​e​ ​r​a​t​i​o​,​ ​b​u​t​ ​m​u​c​h​ ​b​e​t​t​e​r​ ​c​o​m​p​a​t​i​b​i​l​i​t​y​.
						 */
						'3': string
						/**
						 * S​p​e​a​k​i​n​g​ ​o​f​ ​s​i​z​e​s​.​ ​9​0​ ​m​i​n​u​t​e​s​ ​o​f​ ​r​e​c​o​r​d​i​n​g​ ​i​s​…​ ​a​b​o​u​t​ ​2​5​ ​M​B​,​ ​a​n​d​ ​y​o​u​ ​c​a​n​ ​r​e​a​d​ ​e​v​e​r​y​t​h​i​n​g​ ​o​n​ ​s​l​i​d​e​s​.​ ​T​h​e​ ​s​i​z​e​ ​m​a​y​ ​i​n​c​r​e​a​s​e​ ​a​ ​f​e​w​ ​M​B​ ​i​f​ ​c​a​m​e​r​a​s​ ​a​r​e​ ​o​n​ ​d​u​r​i​n​g​ ​l​e​c​t​u​r​e​,​ ​b​u​t​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​a​ ​b​i​g​ ​d​e​a​l​.
						 */
						'4': string
						/**
						 * T​o​ ​a​c​h​i​e​v​e​ ​s​u​c​h​ ​s​i​z​e​ ​I​ ​u​s​e​ ​t​h​e​s​e​ ​c​o​m​m​a​n​d​s​:
						 */
						'5': string
						'6': {
							/**
							 * #​ ​F​o​r​ ​a​u​d​i​o​ ​r​e​c​o​r​d​i​n​g​:
							 */
							'0': string
							/**
							 * #​ ​F​o​r​ ​v​i​d​e​o​ ​r​e​c​o​r​d​i​n​g​:
							 */
							'1': string
							/**
							 * #​ ​T​o​ ​m​e​r​g​e​ ​t​w​o​ ​f​i​l​e​s​:
							 */
							'2': string
						}
						/**
						 * I​ ​u​s​e​d​ ​p​a​r​a​m​e​t​e​r​s​:​ ​W​I​D​T​H​=​{​w​i​d​t​h​}​,​ ​H​E​I​G​H​T​=​{​h​e​i​g​h​t​}​,​ ​F​R​A​M​E​R​A​T​E​=​{​f​r​a​m​e​r​a​t​e​}​,​ ​C​R​F​=​{​c​r​f​}​ ​B​I​T​R​A​T​E​=​{​b​i​t​r​a​t​e​}​.
						 * @param {number} bitrate
						 * @param {number} crf
						 * @param {number} framerate
						 * @param {number} height
						 * @param {number} width
						 */
						'7': RequiredParams<'bitrate' | 'crf' | 'framerate' | 'height' | 'width'>
					}
				}
				'5': {
					/**
					 * H​o​w​ ​i​s​ ​i​t​ ​a​f​t​e​r​ ​o​n​e​ ​s​e​m​e​s​t​e​r​?
					 */
					title: string
					content: {
						/**
						 * A​f​t​e​r​ ​a​l​m​o​s​t​ ​h​a​l​f​ ​o​n​e​ ​t​h​e​ ​y​e​a​r​ ​o​f​ ​W​o​j​t​e​k​ ​e​x​i​s​t​e​n​c​e​ ​I​ ​c​a​n​ ​s​a​y​:​ ​I​t​ ​w​o​r​k​s​ ​g​r​e​a​t​.​ ​I​t​ ​w​a​s​ ​w​o​r​t​h​ ​m​a​k​i​n​g​ ​f​o​r​ ​s​u​r​e​.
						 */
						'0': string
						/**
						 * S​t​a​t​s​ ​y​o​u​ ​a​s​k​i​n​g​ ​f​o​r​?​ ​M​o​r​e​ ​t​h​e​n​ ​6​0​ ​l​e​c​t​u​r​e​s​ ​r​e​c​o​r​d​e​d​ ​w​h​i​c​h​ ​i​s​ ​a​b​o​u​t​ ​2​G​B​ ​i​n​ ​s​i​z​e​.​ ​W​o​j​t​e​k​ ​i​s​ ​a​l​s​o​ ​t​h​e​ ​m​o​s​t​ ​a​t​t​e​n​t​i​v​e​ ​s​t​u​d​e​n​t​ ​w​h​e​n​ ​i​t​ ​c​o​m​e​s​ ​t​o​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​l​e​c​t​u​r​e​s​.
						 */
						'1': string
						/**
						 * I​ ​f​i​n​d​ ​t​h​i​s​ ​p​r​o​j​e​c​t​ ​v​e​r​y​ ​i​n​t​e​r​e​s​t​i​n​g​.​ ​I​ ​g​a​i​n​e​d​ ​a​ ​l​o​t​ ​w​h​i​l​e​ ​d​o​i​n​g​ ​i​t​,​ ​e​v​e​n​ ​t​h​o​u​g​h​ ​I​ ​w​a​s​ ​s​t​a​r​t​i​n​g​ ​t​o​ ​l​o​s​e​ ​p​a​t​i​e​n​t​ ​a​ ​f​e​w​ ​t​i​m​e​s​ ​d​u​e​ ​t​o​ ​b​u​g​s​.​ ​T​h​e​ ​m​o​s​t​ ​i​m​p​o​r​t​a​n​t​ ​t​h​i​n​g​ ​h​o​w​e​v​e​r​ ​i​s​ ​t​h​a​t​ ​I​ ​c​o​u​l​d​ ​h​e​l​p​ ​o​t​h​e​r​s​ ​b​y​ ​a​l​l​o​w​i​n​g​ ​t​h​e​m​ ​t​o​ ​w​a​t​c​h​ ​l​e​c​t​u​r​e​s​ ​l​a​t​e​r​ ​w​h​i​c​h​ ​w​a​s​ ​t​h​e​ ​p​r​i​m​a​r​y​ ​g​o​a​l​.
						 */
						'2': string
					}
				}
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi There!
	 */
	hiThere: () => LocalizedString
	/**
	 * I'm
	 */
	iam: () => LocalizedString
	/**
	 * Cracow
	 */
	cracow: () => LocalizedString
	/**
	 * Software engineer
	 */
	softwareEngineer: () => LocalizedString
	/**
	 * Featured projects
	 */
	featuredProjects: () => LocalizedString
	/**
	 * View my GitHub
	 */
	checkoutGithub: () => LocalizedString
	/**
	 * Message me on Telegram
	 */
	messageTelegram: () => LocalizedString
	/**
	 * Hey! I'm Jakub, software developer from Poland, currently working at IBM. I do numerous projects in various technologies. I also like running 💪
	 */
	siteDescription: () => LocalizedString
	/**
	 * Web game
	 */
	webGame: () => LocalizedString
	/**
	 * Native app
	 */
	nativeApp: () => LocalizedString
	/**
	 * Discord Bot
	 */
	discordBot: () => LocalizedString
	/**
	 * PWA
	 */
	pwa: () => LocalizedString
	/**
	 * Read More…
	 */
	readMore: () => LocalizedString
	/**
	 * Contents
	 */
	contents: () => LocalizedString
	colorLines: {
		/**
		 * Color lines
		 */
		title: () => LocalizedString
		/**
		 * Oct 2020 - now
		 */
		date: () => LocalizedString
		/**
		 * Simple logic game. You need to place at least 5 balls with the same color in one line, seems easy?<br/>How many points can you score?
		 */
		description: () => LocalizedString
	}
	checkers: {
		/**
		 * Checkers
		 */
		title: () => LocalizedString
		/**
		 * Apr 2020
		 */
		date: () => LocalizedString
		/**
		 * It was supposed to be a simple school 3D project. I took it to the next level!<br/>Multiplayer checkers styled to mimic <em>Minecraft</em>.
		 */
		description: () => LocalizedString
	}
	mcwallpaper: {
		/**
		 * Wallpaper generator
		 */
		title: () => LocalizedString
		/**
		 * Mar 2021
		 */
		date: () => LocalizedString
		/**
		 * I thought how would my desktop look all if I would cover it with just a single <em>Minecraft</em> block. It looks gorgeous ❤️
		 */
		description: () => LocalizedString
	}
	planZsl: {
		/**
		 * ZSŁ Timetable
		 */
		title: () => LocalizedString
		/**
		 * Oct 2021
		 */
		date: () => LocalizedString
		/**
		 * Redefining simplicity and reliability for students and teachers. <br/>Offline ready, fast and easy to use app for checking timetables.
		 */
		description: () => LocalizedString
	}
	wojtek: {
		/**
		 * Wojtek
		 */
		title: () => LocalizedString
		/**
		 * /sleepy-student/
		 */
		url: () => LocalizedString
		/**
		 * Oct 2022 - now
		 */
		date: () => LocalizedString
		/**
		 * Wojtek is this one student that is always on time, never misses remote lectures to record and publish them on his webpage…
		 */
		description: () => LocalizedString
	}
	upload: {
		/**
		 * FireFile upload
		 */
		title: () => LocalizedString
		/**
		 * Apr 2021
		 */
		date: () => LocalizedString
		/**
		 * I've always wanted to have fast and simple way to store and share files online. That's my answer to the problem…
		 */
		description: () => LocalizedString
	}
	articles: {
		wojtek: {
			/**
			 * Wojtek · Discord bot for recording lectures
			 */
			title: () => LocalizedString
			/**
			 * I've created Discord bot for recording a remote meeting on Webex or Teams. He joins, mutes self and sends a link to recording after the meeting is done.
			 */
			description: () => LocalizedString
			/**
			 * Wojtek, a bot recording lectures
			 */
			heading: () => LocalizedString
			/**
			 * I think that everyone, at least once, overslept to school.<br />We just sometimes are too lazy to get up. How about using technology to make our lives easier?
			 */
			quote: () => LocalizedString
			sections: {
				'0': {
					/**
					 * But why?
					 */
					title: () => LocalizedString
					content: {
						/**
						 * Here comes the october and with it the brand new semester - new subjects, classes and lectures.
						 */
						'0': () => LocalizedString
						/**
						 * University I study on has made lectures optional (most of them). At the same time they don't want to make remote lectures. If you add to that the fact that most lectures are just inessential to pass exams you get really low presence.
						 */
						'1': () => LocalizedString
						/**
						 * Fortunately most lectures I have are done remote.
						 */
						'2': () => LocalizedString
						/**
						 * Such situation allows for much comfortable knowledge consumption which should lead to more people listening to lectures. At least in theory…
						 */
						'3': () => LocalizedString
						/**
						 * In practice people hope that someone records the meeting so they can watch it later at twice the speed. The problem is when someone is none or because this one person who usually records is absent for some reason.
						 */
						'4': () => LocalizedString
						/**
						 * It would be great to have a friend you can rely on… Meet <em>Wojtek</em> - our new colleague.
						 */
						'5': () => LocalizedString
						/**
						 * Meme with Patrick putting huge pumpkin inside SpongeBob' mouth; With text saying students before session watching lectures
						 */
						'6': () => LocalizedString
					}
				}
				'1': {
					/**
					 * But is it even possible?
					 */
					title: () => LocalizedString
					content: {
						/**
						 * Before making any project I always ask myself: <em>Can something like this be achieved by me?</em>.
						 */
						'0': () => LocalizedString
						/**
						 * To better understand an attempt to create solution I break the problem up to form a few steps. In this case they are:
						 */
						'1': () => LocalizedString
						'2': {
							/**
							 * Launch Chrome in a way I can programmatically control it
							 */
							'0': () => LocalizedString
							/**
							 * Join Webex meeting - pass through process of typing name and Captcha
							 */
							'1': () => LocalizedString
							/**
							 * Record the meeting - both the visuals as well as the audio
							 */
							'2': () => LocalizedString
							/**
							 * Allow for stopping the recording and detect that the meeting has closed
							 */
							'3': () => LocalizedString
							/**
							 * Make it possible for anyone on the Discord server to schedule a recording
							 */
							'4': () => LocalizedString
							/**
							 * Make it intuitive enough for people to use
							 */
							'5': () => LocalizedString
							/**
							 * Repeat everything for Microsoft Teams
							 */
							'6': () => LocalizedString
							/**
							 * Give access to ready recordings
							 */
							'7': () => LocalizedString
						}
						/**
						 * So, I soon began working on the project, bot'll run somewhere in a cloud, so I needed to use Docker to ensure easy portability.
						 */
						'3': () => LocalizedString
						/**
						 * While Docker is great it was actually more difficult to use it, because I needed to program a bot to click visual elements which I couldn't program without seeing the screen. Therefore initially I run the bot locally on my computer. I used a library called <a href="https://pptr.dev/">Puppeteer</a> to easily control the browser.
						 */
						'4': () => LocalizedString
						/**
						 * Now I just need to join the meeting. Webex requests me to solve Captcha 😔 At first I thought it's game over, project impossible to do. But I can just send the screenshot of Captcha to Discord channel and ask anyone for solution. Once solved I can continue joining the meeting.
						 */
						'5': () => LocalizedString
						/**
						 * Screenshot of Webex before entering the meeting
						 */
						'6': () => LocalizedString
						/**
						 * Using the /record command I can tell Wojtek to enter room, he will reply with Captcha to solve after a while.
						 */
						'7': () => LocalizedString
					}
				}
				'2': {
					/**
					 * That works!
					 */
					title: () => LocalizedString
					content: {
						/**
						 * Now I just need to recording the browser tab. I used a library named <a href="https://www.npmjs.com/package/puppeteer-screen-recorder">puppeteer-screen-recorder</a>. It works out of the box, however it doesn't record audio. After using google for a while it was clear: puppeteer doesn't support audio capture in any way 😐
						 */
						'0': () => LocalizedString
						/**
						 * Not everything lost yet, after all I can launch PulseAudio audio server inside Docker. The I can use external program such as ffmpeg to record the audio.
						 */
						'1': () => LocalizedString
						/**
						 * Once the meeting is ended Wojtek can close the Webex tab, merge video with audio into single final file hoping that they are in sync 😅 And then send a message to Discord channel with link to download it.
						 */
						'2': () => LocalizedString
						/**
						 * That way I managed to finish 5 steps - creating MVP. It was time for real scenario tests
						 */
						'3': () => LocalizedString
					}
				}
				'3': {
					/**
					 * Bug fighting
					 */
					title: () => LocalizedString
					content: {
						/**
						 * Obviously software never works first try, Wojtek was no exception. It crashed many times and needed many enhancements to work well.
						 */
						'0': () => LocalizedString
						/**
						 * Entering Teams implementation was quite simple to do once Webex was working. However I stumbled upon unexplained bug. After about 5 minutes into the recording the screen turned completely white. After many and many failed attempt to fix that I was forced to change the basics - drop the recorder library and use <code>Xvfb</code> to simulate real display.
						 */
						'1': () => LocalizedString
						/**
						 * So I modified Wojtek to launch Chrome in fullscreen mode rather then headless one and to use virtual speaker. Now I can record the screen using ffmpeg. There were numerus issues when it comes to starting pulseaudio and X11 as root inside docker. The easiest solution to make it running was to kill their processes, delete <code>/run/pulse*</code> and <code>/tmp/.X1-lock</code> files and then launch the demons.
						 */
						'2': () => LocalizedString
						/**
						 * After a while everything seemed to work fine a reliable. Then out of nowhere Microsoft decided to release Teams update which significantly changed the UI. It obviously broke Wojtek 🙄
						 */
						'3': () => LocalizedString
						/**
						 * There was one time when recording audio failed, but visuals got recorded. What surprised me the most was very small video size. After investigating I noticed that when I record audio I do in stereo effectively doubling audio size for nothing. Thanks to this one bug I've found another one 🤗
						 */
						'4': () => LocalizedString
						/**
						 * There was also a problem I couldn't detect during testing, because it appeared after about 4 minutes of recording. In short the recording got paused for some reason. After investigation I found the cause: ffmpeg, which I use to record, constantly prints some stats such as time to the console. These stats are appended to the stdout buffer available to parent process - Wojtek. However Wojtek doesn't care about this data therefore he never reads it. After about 4 minutes the buffer is full and the operating system suspends executing of ffmpeg until anything from the buffer is consumed. Fixing it was simple: just adding <code> stdio: "ignore" </code> to options object when launching the process 🤦‍♂️
						 */
						'5': () => LocalizedString
					}
				}
				'4': {
					/**
					 * About compression
					 */
					title: () => LocalizedString
					content: {
						/**
						 * Videos are heavy on disk. Fortunately there are some smart people inventing compression algorithms.
						 */
						'0': () => LocalizedString
						/**
						 * The number one priority for me is easy of access for people, therefore recordings are hosted on HTTP server. That allows watching video without needing to download entire file. .mp4 format is well supported in web browsers which makes it ideal candidate for this use case.
						 */
						'1': () => LocalizedString
						/**
						 * But is it really? mp4 is just a container, data inside can be represented using many different codecs. Naturally I tried best codec available out there - h255, however it turns out that it is not yet natively supported on all platforms. Windows operating system even asks you to pay to open such file! In 2022 year 🤯
						 */
						'2': () => LocalizedString
						/**
						 * That's way I decided to go with h254, which offer worse quality to size ratio, but much better compatibility.
						 */
						'3': () => LocalizedString
						/**
						 * Speaking of sizes. 90 minutes of recording is… about 25 MB, and you can read everything on slides. The size may increase a few MB if cameras are on during lecture, but that is not a big deal.
						 */
						'4': () => LocalizedString
						/**
						 * To achieve such size I use these commands:
						 */
						'5': () => LocalizedString
						'6': {
							/**
							 * # For audio recording:
							 */
							'0': () => LocalizedString
							/**
							 * # For video recording:
							 */
							'1': () => LocalizedString
							/**
							 * # To merge two files:
							 */
							'2': () => LocalizedString
						}
						/**
						 * I used parameters: WIDTH={width}, HEIGHT={height}, FRAMERATE={framerate}, CRF={crf} BITRATE={bitrate}.
						 */
						'7': (arg: { bitrate: number, crf: number, framerate: number, height: number, width: number }) => LocalizedString
					}
				}
				'5': {
					/**
					 * How is it after one semester?
					 */
					title: () => LocalizedString
					content: {
						/**
						 * After almost half one the year of Wojtek existence I can say: It works great. It was worth making for sure.
						 */
						'0': () => LocalizedString
						/**
						 * Stats you asking for? More then 60 lectures recorded which is about 2GB in size. Wojtek is also the most attentive student when it comes to listening to lectures.
						 */
						'1': () => LocalizedString
						/**
						 * I find this project very interesting. I gained a lot while doing it, even though I was starting to lose patient a few times due to bugs. The most important thing however is that I could help others by allowing them to watch lectures later which was the primary goal.
						 */
						'2': () => LocalizedString
					}
				}
			}
		}
	}
}

export type Formatters = {}
